// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLxnL6JV_3lyqdXcdFs0tp_5q1lghZ0KI',
    appId: '1:819053778557:web:00772b32ce24d0bd898314',
    messagingSenderId: '819053778557',
    projectId: 'mini-kahoot-5dd3c',
    authDomain: 'mini-kahoot-5dd3c.firebaseapp.com',
    databaseURL: 'https://mini-kahoot-5dd3c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mini-kahoot-5dd3c.firebasestorage.app',
    measurementId: 'G-4M55425F9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8-c4O7k_QVRfKiRFpDega6DK_DZEzr9A',
    appId: '1:819053778557:android:a8469d5531702586898314',
    messagingSenderId: '819053778557',
    projectId: 'mini-kahoot-5dd3c',
    databaseURL: 'https://mini-kahoot-5dd3c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mini-kahoot-5dd3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG3qJpDa5PzxlAGbMN86qzhtm8BtQ_3IM',
    appId: '1:819053778557:ios:329e2d0b4739bd72898314',
    messagingSenderId: '819053778557',
    projectId: 'mini-kahoot-5dd3c',
    databaseURL: 'https://mini-kahoot-5dd3c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mini-kahoot-5dd3c.firebasestorage.app',
    iosBundleId: 'com.example.miniKahootClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG3qJpDa5PzxlAGbMN86qzhtm8BtQ_3IM',
    appId: '1:819053778557:ios:329e2d0b4739bd72898314',
    messagingSenderId: '819053778557',
    projectId: 'mini-kahoot-5dd3c',
    databaseURL: 'https://mini-kahoot-5dd3c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mini-kahoot-5dd3c.firebasestorage.app',
    iosBundleId: 'com.example.miniKahootClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLxnL6JV_3lyqdXcdFs0tp_5q1lghZ0KI',
    appId: '1:819053778557:web:2efe74e744764139898314',
    messagingSenderId: '819053778557',
    projectId: 'mini-kahoot-5dd3c',
    authDomain: 'mini-kahoot-5dd3c.firebaseapp.com',
    databaseURL: 'https://mini-kahoot-5dd3c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mini-kahoot-5dd3c.firebasestorage.app',
    measurementId: 'G-W3T8WQZW6C',
  );
}
